language: node_js
node_js:
  - "18"
  - "20"

env:
  - IN_TRAVIS=yes

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mysql -e 'create database travis_ci_test;'

addons:
  postgresql: "9.4"

services:
  - mysql
